function A = pure_loops_col_row(A)

    for c = 2:1000-1
        for r = 2:1000-1
            A(c, r) = -4.0*A(r,c) + ...
                           A(r-1,c) + ...
                           A(r+1,c) + ...
                           A(r,c-1) + ...
                           A(r,c+1);
        end
    end
end