function A = pure_loops_row_col(A)

    for c = 2:1000-1
        for r = 2:1000-1
            A(r, c) = -4.0*A(c,r) + ...
                           A(c-1,r) + ...
                           A(c+1,r) + ...
                           A(c,r-1) + ...
                           A(c,r+1);
        end
    end
end